<<<<<<< HEAD
# Generated by Django 2.0.7 on 2018-08-02 05:07
=======
# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-31 09:58
from __future__ import unicode_literals
>>>>>>> 6c0dd6c914f92e653ee8e24941335be8686c999b

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('title', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(null=True)),
=======
                ('post', models.CharField(max_length=500)),
>>>>>>> 6c0dd6c914f92e653ee8e24941335be8686c999b
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
