# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-31 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='ty', max_length=500),
        ),
    ]
